MvcProjectCamp/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    [Authorize(Roles="A")]
    public class AboutController : Controller
    {
        AboutManager manager = new AboutManager(new EfAboutDal());
        AboutValidator validations = new AboutValidator();
        public ActionResult Index()
        {
            var values = manager.TGetList();
            return View(values);
        }
        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            ModelState.Clear();
            ValidationResult results = validations.Validate(p);
            if (results.IsValid)
            {
                manager.TInsert(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach(var x in results.Errors)
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                }
            }
            return RedirectToAction("Partial1");
        }
        public PartialViewResult Partial1()
        {
            return PartialView();
        }
    }
}

MvcProjectCamp/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/Templates/webadmin/plugins/jquery/jquery.min.js"></script>

<title>Hakkımızda</title>
<h2>Hakkımızda</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Detay 1</th>
            <th>Detay 2</th>
            <th>Düzenle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.AboutId</td>
                <td>@x.AboutDetails1</td>
                <td>@x.AboutDetails2</td>
                <td><a class="btn btn-warning">Düzenle</a></td>
                <td><a class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>
<button class="btn btn-outline-primary" data-toggle="modal" data-target="#Modal1">Ekle</button>
<div class="modal fade" id="Modal1">
    @Html.Action("Partial1", "About")
</div>

MvcProjectCamp/Views/About/Partial1.cshtml
@model EntityLayer.Concrete.About

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Hakkımızda Ekleme</h3>
        </div>
        <form method="post" action="/About/AddAbout">
            <div class="modal-body">
                @Html.LabelFor(x => x.AboutDetails1)
                @Html.TextBoxFor(x => x.AboutDetails1, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.AboutDetails1, "", new { @style = "color:red" })
                <br />
                @Html.LabelFor(x => x.AboutDetails2)
                @Html.TextBoxFor(x => x.AboutDetails2, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.AboutDetails2, "", new { @style = "color:red" })
                <br />
                @Html.LabelFor(x => x.AboutImage1)
                @Html.TextBoxFor(x => x.AboutImage1, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.AboutImage1, "", new { @style = "color:red" })
                <br />
                @Html.LabelFor(x => x.AboutImage2)
                @Html.TextBoxFor(x => x.AboutImage2, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.AboutImage2, "", new { @style = "color:red" })
                <br />
                <button type="submit" class="btn btn-outline-primary">Ekle</button>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#Modal1').on('shown.bs.modal', function () {
            var form = $('#memberForm');
            $.validator.unobtrusive.parse(form);
        });
    });
</script>